spring:
  client:
    ipAddress: http://192.168.80.210:9901
  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/scm_test?useUnicode=true&characterEncoding=utf8&useSSL=false
    url: jdbc:oracle:thin:@192.168.80.150:1521/orcl
    username: czzhd
    password: czzhd
    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: oracle.jdbc.driver.OracleDriver
    druid:
      max-active: 49
      test-while-idle: true
      time-between-eviction-runs-millis: 599999
      validation-query: SELECT 1 FROM DUAL
      filters: config,wall,stat
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: false
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: /druid/*,*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico
        session-stat-enable: true
        session-stat-max-count: 9
      #StatViewServlet配置，说明请参考Druid Wiki，配置_StatViewServlet配置
      #是否启用StatViewServlet默认值true
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        login-password: admin
        login-username: admin
logging:
  path: ../logs/${spring.application.name}
